services:
  cinelogue-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "cinelogue-data:/var/lib/postgresql/data"

volumes:
  cinelogue-data:
